### ISSUE TITLE
这个断言可以修改一下，前面内循环判断。 if len(masked_token_labels) >= num_to_mask:

### ISSUE THREAD

**Issue by moonblue333** [lonePatient/albert_pytorch#26]

**Comment by DaBinGOGOGO** [comment]
我也遇到了这个情况，按照作者的原始意图，在下面的循环中加上 即可         
if len(masked_token_labels) >= num_to_mask:
                    break

**Comment by Vimos** [comment]
我的也出现了，是数据问题吗？
```
02/23/2020 08:14:06 - INFO - root -   pregenerate training data parameters:
 Namespace(data_dir=PosixPath('data'), data_name='albert', do_data=True, do_lower_case=False, do_split=False, file_num=10, line_per_file=1000000000, masked_lm_prob=0.15, max_ngram=3, max_predictions_per_seq=20, max_seq_len=128, output_dir='data/output', seed=42, short_seq_prob=0.1, vocab_path='vocab.txt')
02/23/2020 08:14:06 - INFO - root -   pregenetate albert_file_0.json
 
Traceback (most recent call last):
  File "/home/vimos/gitee/figurative-albert/prepare_lm_data_ngram.py", line 310, in <module>
    main()
  File "/home/vimos/gitee/figurative-albert/prepare_lm_data_ngram.py", line 294, in main
    max_predictions_per_seq=args.max_predictions_per_seq)
  File "/home/vimos/gitee/figurative-albert/prepare_lm_data_ngram.py", line 217, in create_training_instances
    max_ngram, masked_lm_prob, max_predictions_per_seq, vocab_words))
  File "/home/vimos/gitee/figurative-albert/prepare_lm_data_ngram.py", line 111, in create_instances_from_document
    tokens, max_ngram, masked_lm_prob, max_predictions_per_seq, vocab_words)
  File "/home/vimos/gitee/figurative-albert/prepare_lm_data_ngram.py", line 176, in create_masked_lm_predictions
    assert len(masked_token_labels) <= num_to_mask
AssertionError
```

**Comment by Vimos** [comment]
是加在内循环吧，我看着外循环已经有了
