### ISSUE TITLE
tf模型转pytorch模型报错？

### ISSUE THREAD

**Issue by ghost** [lonePatient/albert_pytorch#63]
Traceback (most recent call last):
  File "/home/xyf/albert/albert_pytorch/convert_albert_tf_checkpoint_to_pytorch.py", line 63, in <module>
    args.pytorch_dump_path)
  File "/home/xyf/albert/albert_pytorch/convert_albert_tf_checkpoint_to_pytorch.py", line 34, in convert_tf_checkpoint_to_pytorch
    load_tf_weights_in_albert(model, config, tf_checkpoint_path)
  File "/home/xyf/albert/albert_pytorch/model/modeling_albert.py", line 87, in load_tf_weights_in_albert
    assert pointer.shape == array.shape
AssertionError: (torch.Size([128]), (1024,))

**Comment by lonePatient** [comment]
应该是模型版本不一致，中文albert权重版本有两个，一个是谷歌的，一个是bright的，分别对应不同的模型文件，如果是这个问题的话，你看下readme.md.

**Comment by xueyongfu** [comment]
是的，换了谷歌的模型后转成功了。bright的tf模型该怎么转pytorch呢？
