### ISSUE TITLE
运行run_classifier.py出现AttributeError: 'ModuleList' object has no attribute 'LayerNorm'   

### ISSUE THREAD

**Issue by leiguo2018** [lonePatient/albert_pytorch#8]
错误信息：
```
Traceback (most recent call last):
  File "./albert_pytorch/run_classifier.py", line 293, in <module>
    main()
  File "./albert_pytorch/run_classifier.py", line 269, in main
    train(args, train_dataloader, valid_dataloader, metrics, model)
  File "./albert_pytorch/run_classifier.py", line 73, in train
    outputs = model(**inputs)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kesci/work/albert_pytorch/model/modeling_albert.py", line 814, in forward
    head_mask=head_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kesci/work/albert_pytorch/model/modeling_albert.py", line 666, in forward
    head_mask=head_mask)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kesci/work/albert_pytorch/model/modeling_albert.py", line 392, in forward
    layer_outputs = layer_module(hidden_states, attention_mask, i, head_mask[i])
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/kesci/work/albert_pytorch/model/modeling_albert.py", line 353, in forward
    attention_output_pre = self.output.LayerNorm(attention_output)
  File "/opt/conda/lib/python3.6/site-packages/torch/nn/modules/module.py", line 585, in __getattr__
    type(self).__name__, name))
AttributeError: 'ModuleList' object has no attribute 'LayerNorm'
```
使用Python 3.6和Torch 1.1.0，查了官方文档这个版本的Torch已经有LayerNorm，能否帮我看看问题出在哪里，多谢！

**Comment by lonePatient** [comment]
@leiguo2018 完整的运行命令？如果使用的预训练权重 share_type为all,   其余选择只是自己训练模型的时候选择，你这个应该时share_type设置问题

**Comment by leiguo2018** [comment]
> @leiguo2018 完整的运行命令？如果使用的预训练权重 share_type为all, 其余选择只是自己训练模型的时候选择，你这个应该时share_type设置问题

```
! python3 ./albert_pytorch/run_classifier.py \
    --train_max_seq_len 512 --eval_max_seq_len 512 --share_type attention --do_train --do_eval \
    --evaluate_during_training --train_batch_size 5 --eval_batch_size 5 --gradient_accumulation_steps 4 \
    --num_train_epochs 3 --overwrite_output_dir --overwrite_cache 
```
是的，使用tf预训练权重转换到torch预训练权重时候的设置的确是share_type为all。刚刚将上面的运行命令改为`--share_type all`的确不报这个错误了，而是新报了`RuntimeError: CUDA out of memory.`的错误。
所以错误`'ModuleList' object has no attribute 'LayerNorm'`的来源是因为在转换权重时设置share_type为all，而在训练时设置share_type为attention吗？但是我之前看到别的issue提问转换权重时只能设置为all，设置为别的选项会报错，那我现在想在后面的训练过程中使用share_type为attention的网络改怎么做呢？

**Comment by lonePatient** [comment]
@leiguo2018 原作者提供的只有share_type=all的权重，如果时基于预训练模型的话，目前这个只能设置为all, 如果只要attention的话，你可以简单修改下，目前版本share_type=attention 或者ffn，只是适合训练自己的albert模型

**Comment by leiguo2018** [comment]
了解啦，多谢！
